const mongoose = require('mongoose');

const jobSchema = new mongoose.Schema({
    companyId: {
        type: mongoose.Schema.Types.ObjectId,
        ref: 'Company',
        required: true
    },

    // Job Details
    title: { type: String, required: true },
    description: { type: String, required: true },
    jobType: {
        type: String,
        enum: ['Full-time', 'Part-time', 'Internship', 'Contract'],
        required: true
    },

    // Location
    location: { type: String, required: true },
    workMode: {
        type: String,
        enum: ['On-site', 'Remote', 'Hybrid'],
        default: 'On-site'
    },

    // Compensation
    salary: {
        min: Number,
        max: Number,
        currency: { type: String, default: 'INR' }
    },
    stipend: Number, // For internships

    // Requirements
    requiredSkills: [String],
    preferredSkills: [String],
    minCGPA: { type: Number, min: 0, max: 10 },
    minEducation: {
        type: String,
        enum: ['10th', '12th', 'Diploma', 'Bachelors', 'Masters', 'PhD']
    },
    eligibleBranches: [String],
    experienceRequired: {
        min: { type: Number, default: 0 },
        max: Number
    },

    // Application Settings
    applicationDeadline: Date,
    openings: { type: Number, default: 1 },
    isActive: { type: Boolean, default: true },

    // Selection Process
    selectionProcess: [{
        stage: {
            type: String,
            enum: ['Application Review', 'Online Assessment', 'Technical Interview', 'AI Interview', 'Managerial Round', 'HR Round']
        },
        description: String,
        duration: Number // in minutes
    }],

    // Applications
    applications: [{
        type: mongoose.Schema.Types.ObjectId,
        ref: 'Application'
    }],
    totalApplications: { type: Number, default: 0 },

    // Generated by AI
    aiGenerated: {
        description: Boolean,
        questionsGenerated: Boolean
    }

}, { timestamps: true });

jobSchema.index({ companyId: 1, isActive: 1 });
jobSchema.index({ requiredSkills: 1 });
jobSchema.index({ applicationDeadline: 1 });

module.exports = mongoose.model('Job', jobSchema);
